checks:
  javascript: true
build:
  nodes:
    coverage:
      tests:
        override:
          - command: yarn test
            coverage:
              file: ./coverage/clover.xml
              format: clover
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    tests: true
